export const canvasClientEvents = {
  join: "canvas:join",
  leave: "canvas:leave",
  historyRedo: "canvas:room:history:redo",
  historyUndo: "canvas:room:history:undo",
  presenceUpdate: "canvas:presence:update",
  shapeLockClaim: "canvas:shape:lock:claim",
  shapeLockRelease: "canvas:shape:lock:release",
  shapePatch: "canvas:room:shape:patch",
  shapePreview: "canvas:shape:preview",
  shapePreviewClear: "canvas:shape:preview:clear",
  viewportLoaded: "canvas:viewport:loaded",
} as const;

export const canvasServerEvents = {
  checkpoint: "canvas:room:checkpoint",
  error: "canvas:error",
  joined: "canvas:joined",
  operation: "canvas:operation",
  presenceLeave: "canvas:presence:leave",
  presenceUpdate: "canvas:presence:update",
  shapeLockAccepted: "canvas:shape:lock:accepted",
  shapeLockRejected: "canvas:shape:lock:rejected",
  shapeLockRelease: "canvas:shape:lock:release",
  shapeLockUpdate: "canvas:shape:lock:update",
  shapePatch: "canvas:room:shape:patch",
  shapePreview: "canvas:shape:preview",
  shapePreviewClear: "canvas:shape:preview:clear",
  shapesHydrate: "canvas:room:shapes:hydrate",
  loadedRegionsUpdate: "canvas:room:loaded-regions:update",
  syncRequired: "canvas:sync:required",
} as const;
